image: docker:latest

services:
  - docker:dind

before_script:
  - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY

stages:
  - build
  - test
  - deploy

metric-flow-image-build:
  stage: build
  script:
    - docker build -t "$CI_REGISTRY_IMAGE":latest .
    - docker push "$CI_REGISTRY_IMAGE":latest
  only:
    - master
  tags:
    - docker

proxy-image-build:
  stage: build
  script:
    - docker build -t "$CI_REGISTRY_IMAGE":nginx .
    - docker push "$CI_REGISTRY_IMAGE":nginx
  tags:
    - docker

production-deploy:
  stage: deploy
  script:
    - docker-compose up -d --abort-on-container-exit
  tags:
    - deploy