FROM microsoft/dotnet:sdk

LABEL author="Anton Mazurov"

COPY . /app

WORKDIR /app/API/MetricFlow.WebApi

RUN dotnet publish -c Release -o out

ENV ASPNETCORE_ENVIRONMENT Production
ENV ASPNETCORE_URLS http://*:5000
EXPOSE 5000

ENTRYPOINT ["dotnet", "out/MetricFlow.WebApi.dll"]