version: '2.1'

networks:
  metricflow-docker-net:
    driver: bridge

services:
  metric-flow:
    container_name: 'metric-flow-app'
    image: registry.gitlab.com/outworkanton/metricflow:latest
    restart: on-failure
    depends_on:
      - postgres
    expose:
      - "5000"
    networks:
      - metricflow-docker-net
    healthcheck:
      test: curl --silent --fail http://localhost:5000/healthcheck || exit 1
      interval: 10s
      timeout: 10s
      retries: 3

  postgres:
    container_name: 'postgres-db'
    image: postgres:latest
    ports:
      - "5432"
    restart: always
    environment:
      POSTGRES_USER: "convex"
      POSTGRES_PASSWORD: 2sywbMud
      POSTGRES_DB: "metric_flow_db"
    networks:
      - metricflow-docker-net

  proxy:
    container_name: 'reverse-proxy'
    image: registry.gitlab.com/outworkanton/metricflow:nginx
    restart: always
    ports:
      - "5000:5000"
    networks:
      - metricflow-docker-net
    depends_on:
        metric-flow:
          condition: service_healthy