version: '3.4'

networks:
  metricflow-docker-net:
    driver: bridge

services:
  metric-flow:
    container_name: 'metric-flow'
    image: outwork/metric-flow:latest
    depends_on:
      - "postgres"
    expose:
      - "5000"
    networks:
      - metricflow-docker-net

  postgres:
    container_name: 'postgres'
    image: postgres:latest
    ports:
      - "5432"
    restart: always
    environment:
      POSTGRES_USER: "convex"
      POSTGRES_PASSWORD: 2sywbMud
      POSTGRES_DB: "metric_flow_db"
    networks:
      - metricflow-docker-net

  proxy:
    container_name: 'proxy'
    image: nginx:latest
    restart: always
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "5000:5000"
    networks:
      - metricflow-docker-net
    depends_on:
        - "metric-flow"